server:
  port: 9999
  context-path: /sso

spring:
  datasource:
    platform: h2
# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter
security:
  oauth2:
    resource:
      filter-order: 3

#logging:
#  level:
#    org.springframework.security: DEBUG
